# Generated by Django 4.1 on 2022-11-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="currently_playing",
        ),
        migrations.RemoveField(
            model_name="room",
            name="votes_to_skip",
        ),
    ]
